modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="legions"
version="1.0.0"
displayName="Legions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="15735, MCreator"

[[dependencies.legions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




